### PR TITLE
refactor: independent of babel runtime

### PR DESCRIPTION
**Pull request by tejasmanohar**
Solves #5

// cc @dead-horse

### CODE REVIEW

**Comment by tejasmanohar** [comment]
The other advantage of this is that it doesn't force the user to use Babel or specifically, the live transpiling process- especially the latter since it's unfavorable in production for perf reasons.

**Comment by dead-horse** [comment]
LGTM

**Comment by qw3rtman** [comment]
:+1:

**Comment by tejasmanohar** [comment]
@dead-horse I guess this warrants v2.0? Seems early but big, breaking change :P

**Comment by dead-horse** [comment]
published 2.0.0 to npm. :)

**Comment by tejasmanohar** [comment]
whoop! @dead-horse

**Comment by tejasmanohar** [comment]
@dead-horse: on a side note, small thing-- it says "An" in description on github when it should say "A" but Readme has it correctly. mind changing? :D

**Comment by dead-horse** [comment]
fixed.  :(

**Comment by tejasmanohar** [comment]
:)

**Pull request merged**
